### ISSUE TITLE
Can’t add blocks to matrix inside Supertable after initial creation

### ISSUE THREAD

**Issue by ockam** [engram-design/SuperTable#154]
### Description

When adding a new matrix field to a Supertable, I can add all the blocks I want to the matrix, but after the field is saved with the new matrix, it’s not possible to save it again after having added new blocks to the matrix field. I always receive an error: `Undefined index: name`

### Steps to reproduce

1. Add a matrix field to a Supertable
2. Add some blocks to the matrix
3. Save the Supertable field
4. Edit the Supertable field again
5. Add new blocks to the matrix inside the Supertable
6. Save the Supertable field -> will generate the error

### Additional info

- Plugin version: 2.0.6
- Craft version: 3.0.5

**Comment by engram-design** [comment]
I believe this was an issue for Matrix > Super Table > Matrix setups, and was fixed in the last few versions. From memory, can you recall if you created this field in a previous version of Super Table? If so, you may have to delete the entire field and start again, due to issues. This however, shouldn't be an issue in the latest Super Table, and for Super Table > Matrix combinations.

Are you able to confirm if this issue occurs on a brand new field setup? Testing here doesn't seem to throw an issue.

**Comment by ockam** [comment]
This was a fresh install with a new field of type Super Table > Matrix.

Just upgraded to 2.0.7 and created a new field with a Super Table > Matrix combination and still have the issue.

One thing I noticed is that on initial creation of the field, when I add new block to the matrix, the block handle do not autocomplete. When I edit the field and try to add new matrix block, the handle do autocomplete.

Error is here:

```
 in /Users/plemieux/DEV/Sovar/www/vendor/craftcms/cms/src/fields/Matrix.php at line 193

        foreach ($blockTypes as $key => $config) {
            if ($config instanceof MatrixBlockType) {
                $this->_blockTypes[] = $config;
            } else {
                $blockType = new MatrixBlockType();
                $blockType->id = $key;
                $blockType->fieldId = $this->id;
                $blockType->name = $config['name']; // <- line 193
                $blockType->handle = $config['handle'];
```
And here’s a dump of blockTypes before the loop:
```
array (size=3)
  6 => 
    array (size=3)
      'name' => string 'Texte' (length=5)
      'handle' => string 'texte' (length=5)
      'fields' => 
        array (size=1)
          30 => 
            array (size=8)
              ...
  7 => 
    array (size=3)
      'name' => string 'Image' (length=5)
      'handle' => string 'image' (length=5)
      'fields' => 
        array (size=1)
          31 => 
            array (size=8)
              ...
  'new1' => 
    array (size=1)
      'fields' => 
        array (size=1)
          'new1' => 
            array (size=8)
              ...
```
I tested in the latest versions of Chrome and Firefox. There’s no JS error in the console.

**Comment by engram-design** [comment]
Very interesting, it does sound like a JS error, but I note you're not getting any. I'll give this another look.

**Comment by ockam** [comment]
I wonder if this can be an issue with my cpresources folder?

Do you know if there’s a way to recreate it? I don’t see any explicit command in the CLI fot that.

**Comment by ockam** [comment]
Just learned that it will autoregenerate if it’s deleted.

I tried but the bug is still there.

**Comment by ockam** [comment]
Made myself a vanilla install where I was able to edit the ”matrix inside supertable“ without any error.

Still haven’t figured out what in my initial install is going wrong but I have noticed 2 things while inspecting each installs.

1. In the vanilla install, Garnish log this message when adding a new matrix field:
`Double-instantiating a modal on an element`

2. when I inspect the source after creating the new field, the hidden inputs for the matrix field are different.

In the working vanilla install:
```
<input class="hidden" name="types[verbb\supertable\fields\SuperTableField][blockTypes][1][fields][2][typesettings][blockTypes][new1][name]">
<input class="hidden" name="types[verbb\supertable\fields\SuperTableField][blockTypes][1][fields][2][typesettings][blockTypes][new1][handle]">
```
In the NON-working install:
```
<input class="hidden" name="types[craft\fields\Matrix][blockTypes][new1][name]">
<input class="hidden" name="types[craft\fields\Matrix][blockTypes][new1][handle]">
```

**Comment by marcdebiak** [comment]
I'm having a similar issue when trying to add a Matrix field within Super Table.

```
Database Exception – yii\db\Exception
SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for integer: "new1"
The SQL being executed was: SELECT EXISTS(SELECT *
FROM "kb_matrixblocktypes"
WHERE ("kb_matrixblocktypes"."name"='Text Column') AND ("kb_matrixblocktypes"."fieldId"='new1'))
Error Info: Array
(
    [0] => 22P02
    [1] => 7
    [2] => ERROR:  invalid input syntax for integer: "new1"
)
↵
Caused by: PDOException
SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for integer: "new1"
in /opt/kenburns/vendor/yiisoft/yii2/db/Command.php at line 1258
```

**Comment by skramstad** [comment]
Hi.

I got the same error. I see one curious thing in the error console (PHP Notice). Maybe its supposed to be like this. I'll try to explain.

My setup is like this: matrix (level 1) -> superTable (level 2) -> Matrix field (level 3)

The new field I added inside Matrix field in level 3. 
Some of the code shows up at the end in level 1 instead of inside the new level 3.

The error shows the new field in level 3 like this (seems correct) but missing the Name and Handle:
`
'new1' => [

    'fields' => [
        'new1' => [
            'name' => 'Button Title',
            'handle' => 'buttonTitle',
            'instructions' => '',
            'required' => '1',
            'type' => 'craft\\fields\\PlainText',
            'typesettings' => [
                'placeholder' => '',
                'charLimit' => '',
                'code' => '',
                'multiline' => '',
                'initialRows' => '4',
                'columnType' => 'text',
            ],
        ],
        'new2' => [
            'name' => 'Button Email',
            'handle' => 'buttonEmail',
            'instructions' => '',
            'required' => '1',
            'type' => 'craft\\fields\\Email',
        ],
    ],
],
`

However, further down this shows up below all other existing level 1 fields in my matrix. Only the name and handle.
`
'new1' => [

    'name' => 'Email',
    'handle' => 'email',
],
`

It seems like its trying to add a new level 1 field in my matrix, instead of inside the level 3 matrix that is inside my supertable. But as expected it has no settings etc and then fails.

I hope this was helpfull. 

@marcdebiak do you see your new field further down in the error message as well? I recon it might be below your last matrix field and above.`  'minBlocks' => '',
 'maxBlocks' => '',`

**Comment by nettum** [comment]
I'm having the same issue when I try to add a new block type to the Matrix inside a Super Table:
![image](https://user-images.githubusercontent.com/798156/40912606-5af4f33c-67f2-11e8-925d-f73e20358532.png)

I can edit the `textBlock`-type, but as soon as I try to add another block I get this error:
`vendor/craftcms/cms/src/fields/Matrix.php` at line 193:
![image](https://user-images.githubusercontent.com/798156/40912504-0ca32316-67f2-11e8-8df8-e79dc4a50f04.png)

This actually seems to be related the what language I've selected on my user-account.
![image](https://user-images.githubusercontent.com/798156/40913283-67c3b5ec-67f4-11e8-8b5f-3b8ef4bc4e91.png)
For me it seems to work everytime I set language back to "English" and fail everytime I set language to "norsk bokmål".
@ockam Could you check if this is the case for you if you are running another language than "English"?

**Comment by ockam** [comment]
@nettum you nailed it!

I confirm that when my user is on French, I have the bug and when I switch to English, I don’t.

**Comment by skramstad** [comment]
Thanks @nettum! The same "fix" works for this problem as well https://github.com/verbb/super-table/issues/161

**Comment by engram-design** [comment]
Thanks all for the investigation here, should be fixed in [2.0.8](https://github.com/verbb/super-table/releases/tag/2.0.8). You may need to re-create your fields from the start due to incorrect namespacing being generated.
