### ISSUE TITLE
Updating from 0.2.9 Failed

### ISSUE THREAD

**Issue by madebyshape** [engram-design/SuperTable#34]
I'm having a few issues with having a Matrix field inside a SuperTable field and noticed the latest version seemed to fix a few issues regarding this.

I've tried to update from 0.2.9 to 0.3.5 (pretty sure I only downloaded this add-on a month or so ago - So well done for all these updates!) but when I do the update fails and rolls back.

I've tried following your steps of renaming the tables from:

craft_supertablecontent_HANDLE_elementId_locale_unq_idx to craft_supertablecontent_NUMBER_HANDLE_elementId_locale_unq_idx

But my tables look like:

craft_supertablecontent_column

I understand the 'column' bit is the HANDLE, but where do I get the NUMBER bit from? 

and also my tables don't have "_elementId_locale_unq_idx" after them, is this correct and do I need to add this on?

Bit confused!

Thanks

**Comment by engram-design** [comment]
No worries - its a little confusing anyway! When the update fails, you should get a line in your `craft.log` file with something like `[error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[42000]: Syntax error or access violation: 1059 Identifier name 'craft_supertablecontent_NUMBER_HANDLE_elementId_locale_unq_idx' is too long.`. Can you confirm if you see this? If not, I can walk you through tracking down the Matrix field id.

**Comment by madebyshape** [comment]
Thanks for the quick reply (And my slow response!)

I've managed to track down this error, not exactly same as yours:

**[error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[42000]: Syntax error or access violation: 1059 Identifier name 'craft_supertablecontent_9_mediavideoaudio_elementId_locale_unq_idx' is too long. The SQL statement executed was: CREATE TABLE `craft_supertablecontent_9_mediavideoaudio`**

**Comment by madebyshape** [comment]
I managed to go through this and rename around 8 tables (Screenshot attached)

But there is still 5 that I can't get the numbers for. Trying the update still throws an error that it can't update, but nothing is showing in the logs anymore.
![screen shot 2015-10-05 at 11 47 34](https://cloud.githubusercontent.com/assets/10700908/10278657/e4773106-6b56-11e5-8796-4274f38bdcb0.png)

**Comment by engram-design** [comment]
Are those other fields inside Matrix fields? As in `columnlist`, `listcirclescontent`, etc. If they're just solo Super Table fields, the table isn't prefixed. Its very likely it could be a separate issue. Feel free to get it touch via Slack if you need some hands-on help.

**Comment by madebyshape** [comment]
Only 1 of them is not inside a Matrix which is the _sites one.

I've tried again after finding the values etc but it's still throwing errors and rolling back.
![screen shot 2015-10-05 at 14 12 17](https://cloud.githubusercontent.com/assets/10700908/10281263/361a45a2-6b6b-11e5-8c38-9d2ce605ac6d.png)

**Comment by gabrielmoreira** [comment]
I'm having this error... 
```
2015/12/11 03:22:57 [error] [system.db.CDbCommand] Falha ao executar CDbCommand::execute(): SQLSTATE[42000]: Syntax error or access violation: 1059 Identifier name 'craft_supertablecontent_101_redessociais_elementId_locale_unq_idx' is too long. A declaração SQL executada foi: CREATE TABLE `craft_supertablecontent_101_redessociais` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `elementId` int(11) NOT NULL,
  `locale` char(12) COLLATE utf8_unicode_ci NOT NULL,
  `field_icone` text COLLATE utf8_unicode_ci,
  `field_linkTo` text COLLATE utf8_unicode_ci,
  `field_nome` text COLLATE utf8_unicode_ci,
  `dateCreated` datetime NOT NULL,
  `dateUpdated` datetime NOT NULL,
  `uid` char(36) COLLATE utf8_unicode_ci NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `craft_supertablecontent_101_redessociais_elementId_locale_unq_idx` (`elementId`,`locale`),
  KEY `craft_supertablecontent_101_redessociais_locale_fk` (`locale`),
  CONSTRAINT `craft_supertablecontent_101_redessociais_elementId_fk` FOREIGN KEY (`elementId`) REFERENCES `craft_elements` (`id`) ON DELETE CASCADE,
  CONSTRAINT `craft_supertablecontent_101_redessociais_locale_fk` FOREIGN KEY (`locale`) REFERENCES `craft_locales` (`locale`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci.
2015/12/11 03:22:57 [error] [application] CDbCommand falhou ao executar o comando SQL: SQLSTATE[42000]: Syntax error or access violation: 1059 Identifier name 'craft_supertablecontent_101_redessociais_elementId_locale_unq_idx' is too long (/var/www/craft/app/framework/db/CDbCommand.php:358)
2015/12/11 03:22:57 [error] [application] #0 /var/www/craft/plugins/supertable/migrations/m150901_144609_superTable_fixForContentTables.php(56): CDbCommand->execute()
#1 /var/www/craft/app/etc/db/BaseMigration.php(31): Craft\m150901_144609_superTable_fixForContentTables->safeUp()
#2 /var/www/craft/app/services/MigrationsService.php(149): Craft\BaseMigration->up()
#3 /var/www/craft/app/services/MigrationsService.php(91): Craft\MigrationsService->migrateUp('m150901_144609_...', Object(Craft\SuperTablePlugin))
#4 /var/www/craft/app/etc/updates/Updater.php(199): Craft\MigrationsService->runToTop(Object(Craft\SuperTablePlugin))
#5 /var/www/craft/app/services/UpdatesService.php(727): Craft\Updater->updateDatabase(Object(Craft\SuperTablePlugin))
#6 /var/www/craft/app/controllers/UpdateController.php(360): Craft\UpdatesService->updateDatabase('supertable')
#7 /var/www/craft/app/framework/web/actions/CInlineAction.php(49): Craft\UpdateController->actionUpdateDatabase()
#8 /var/www/craft/app/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#9 /var/www/craft/app/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#10 /var/www/craft/app/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 /var/www/craft/app/framework/web/CWebApplication.php(282): CController->run('updateDatabase')
#12 /var/www/craft/app/etc/web/WebApp.php(924): CWebApplication->runController('update/updateDa...')
#13 /var/www/craft/app/etc/web/WebApp.php(256): Craft\WebApp->_processUpdateLogic()
#14 /var/www/craft/app/framework/base/CApplication.php(184): Craft\WebApp->processRequest()
#15 /var/www/craft/app/index.php(62): CApplication->run()
#16 /var/www/html/index.php(40): require_once('/var/www/craft/...')
#17 {main}
2015/12/11 03:22:57 [error] [application] Failed to apply migration: m150901_144609_superTable_fixForContentTables (time: 2.246s)
2015/12/11 03:22:57 [error] [application] Migration failed for plugin SuperTable. All later SuperTable migrations are canceled.
```

**Comment by engram-design** [comment]
@gabrielmoreira Have you looked through the above and also read [Updating from 0.3.4 to 0.3.5](https://github.com/engram-design/SuperTable#updating-from-034-to-035)?

In your particular case, you'll need to rename your database table from `craft_supertablecontent_redessociais` to `craft_supertablecontent_101_redessociais` manually

**Comment by gabrielmoreira** [comment]
@engram-design Sorry, i didn't.
Solved my problem.

One question:
I have a big matrix field (~20 blocks) with blocks and supertables , and some supertables has matrix fields.
With Craft 2.4, it's ok to save this big field, but with Craft 2.5 it's very slow to change my matrix>supertable>matrix fields... The modal on UI is very slow... Is it because Craft 2.5 UI? Or do you think it can be some js problem?

**Comment by engram-design** [comment]
Awesome - great to hear! I haven't personally noticed this, but haven't gone to the scale you're talking about. Let me test a few things out and I'll get back to you.

**Comment by madebyshape** [comment]
Sorry to reopen this, but for some reason I haven't finished this off (I thought I had!) 

But i'm having the same issue as before where it gets to a certain point and then I can't get anymore values. I can't remember how we fixed this... (Think you helped me via Slack!) 

Is there anyway of figuring out what these values should be?

**Comment by ijy** [comment]
@ghost Did you ever get it figured out? I've tried the manual update method but still have the same problem and the rollback doesn't work either.
