### ISSUE TITLE
Removing an item from a super-table list does not refresh the page, does not save in the draft, and breaks previewing changes

### ISSUE THREAD

**Issue by andreimoment** [engram-design/SuperTable#368]
### Description
Removing an item from a super-table list does not refresh the page, does not save in the draft, and breaks previewing changes for any further edits in any content modules

### Steps to reproduce

Given a super table with field A referencing an entry, and field B - a redactor field, where **the super table is on a matrix field**

1. Add an item to the super table in preview mode
2. Add another item
3. Remove the second item
4. The preview should refresh, but doesn't
5. Editing this or any other content module on the page no longer refreshes the preview
6. Force-reload the editor page, open preview again, the second item is still on the page

See this screenshot: there are three items on the left as one was removed. But, the page on the right shows four items. This persists with full page reload -- the edit did not take place.

<img width="1066" alt="super-table--removing-an-item-fail" src="https://user-images.githubusercontent.com/6190/86860507-d5dfa100-c079-11ea-8d4f-c7675b733bf5.png">

Adding and reordering items works OK.  Removing an item 

### Additional info

- Plugin version: 2.5.1
- Craft version: 3.4.27

**Comment by benatleith** [comment]
I'm seeing very similar behaviour to @andreimoment except that adding new table rows or editing existing ones is not reflected in the preview pane at all (either before or after attempting to remove a row).

I also noticed an error in my browser's console:

![Screenshot 2020-07-12 at 23 42 38](https://user-images.githubusercontent.com/15892203/87258358-d40f4680-c49a-11ea-9f3c-cb64f69c7242.png)

- Plugin version: 2.5.1
- Craft version: 3.4.27

**Comment by andreimoment** [comment]
This is a high priority issue for my client, so in searching for solutions, I tried downgrading the plugin, and then also craftcms and testing the behavior with each minor point version of both. 

I found that the plugin seems to work OK at 2.4.9, after I downgraded craft to 3.4.21.

I then upgraded craft to 3.4.27 (latest as of today) and left the plugin at 2.4.9, and the behavior remained functional. The live preview  takes about a minute to refresh after removing an item but that's less worse than broken behavior. 

@meestaben hope this helps while we're waiting for a fix.

Also, note, in my case the super table is on a matrix field.

**Comment by engram-design** [comment]
@andreimoment Interesting. There were actually issues with both Craft and Super Table that caused issues with Live preview in very specific circumstances. Namely, when min rows was set (see https://github.com/craftcms/cms/issues/6154 and https://github.com/verbb/super-table/issues/361).

I'll look into this shortly, but just wanted to confirm in both cases if we're dealing with a lone Super Table field, or a Super Table field nested in a Matrix field (or vice versa). This can make all the difference, and if possible, I'd love it if you're able to test some of these options?

**Comment by engram-design** [comment]
@meestaben Just wanted to confirm your field setup so I can reproduce this. I've tested with a combination of fields, or all the latest versions but haven't gotten that error to be thrown.

**Comment by engram-design** [comment]
@meestaben Actually, think I might have gotten to the bottom of this.

To get the fix early, change your `verbb/super-table` requirement in composer.json to:

```
"require": {
  "verbb/super-table": "dev-craft-3 as 2.5.1",
  "...": "..."
}
```

Then run `composer update`

**Comment by andreimoment** [comment]
@engram-design thank you, this fixed the issue completely.

Removing items from the supertable is now instantaneously reflected in the preview.

**Comment by engram-design** [comment]
Fixed in [2.5.2](https://github.com/verbb/super-table/releases/tag/2.5.2)

**Comment by jeffaglenn** [comment]
This is unfortunately still happening to me in v2.6.1 & Craft v3.5.5. As soon as an entry becomes a Draft a Super Table field within a Matrix is unusable and when the changes are published the content reverts back to before the changes. When using Live Preview only the first change is shown but every subsequent change is ignored. Attaching a couple of gifs showing the issue.

![saveasdraft](https://user-images.githubusercontent.com/34280463/90800829-c8edd880-e2da-11ea-8d09-372436a4a5d0.gif)

![livepreview](https://user-images.githubusercontent.com/34280463/90800846-ce4b2300-e2da-11ea-8a63-ba9044d60501.gif)

**Comment by engram-design** [comment]
@jeffaglenn Looks like you might be right, following up again...

**Comment by engram-design** [comment]
@jeffaglenn Ah, Craft have not released their fix for this yet, see https://github.com/craftcms/cms/issues/6480

**Comment by brandonkelly** [comment]
Craft 3.5.6 is out now with that fix.
