### ISSUE TITLE
Setting supertable field as static doesn't show the fields - just labels (Craft 4)

### ISSUE THREAD

**Issue by DenyEs** [engram-design/SuperTable#464]
As the title states, when I create a Super Table field and set it as static, you can only see the label of the field. At first I though it's just hidden and might be a CSS issue but it turns out it doesn't populate the DOM with inputs whatsoever.

1. Create a supertable field and set to static
2. Add a field to the section (I have mine in globals)
3. Visit the section

- Plugin version: 3.0.0-beta.3
- Craft version: 4.0.1
- Multi-site: No

**Comment by mscherr-fastspot** [comment]
Having the same issue as above, but something else to note:

The table **does** show when you set the "Min Rows" to at least "1" (with "Static field" checked as well). However, you aren't able to save the entry upon doing so (even if all the fields in the super table are not required).

- Plugin version: 3.0.0-beta.3
- Craft version: 4.0.2
- Multi-site: No

**Comment by engram-design** [comment]
Fixed for the next release. To get the fix early, change your `verbb/super-table` requirement in `composer.json` to:

```
"require": {
  "verbb/super-table": "dev-craft-4 as 3.0.0-beta.3",
  "...": "..."
}
```

Then run `composer update`.

**Comment by DenyEs** [comment]
I changed my composer.json file to get the fix early just to test it out and it doesn't seems to work. Somehow it made one field work but it didn't work for the rest of them. I set it to static and it doesn't make any change if there is max row set to 1 or blank, it doesn't show the fields at all. I tried to resave fields that have been previously created and created new fields to see if it helps but it didn't. The amount of fields inside doesn't make any difference either.

**Comment by engram-design** [comment]
Hmm, does re-saving the fields help at all? It shouldn't, as this was a pretty simple mistake when rendering the field inputs HTML https://github.com/verbb/super-table/commit/8e17618341b6453be920a147d37eb5a32263283f

**Comment by DenyEs** [comment]
It's really strange, so re-saving doesn't help but when I create a new one, it works, however if you create another one, it's gone again and I can only see labels for that particular field, the first one is all good tho. I tried different handles and titles just to make sure that's not the problem, all sorts of field combination inside of the supertable, still no luck. Would it help if I sent over my database with composer.json file? The only thing that change since opening the ticket is Craft version, that is now 4.0.2 and of course I applied the early fix for this plugin.

<img width="1346" alt="Screenshot 2022-05-17 at 09 17 07" src="https://user-images.githubusercontent.com/18517642/168763981-846f6e89-ad12-406b-ad39-1f46c4831f5a.png">

**Comment by DenyEs** [comment]
I just noticed something else as well. When I am in globals on a tab that doesn't have supertable fields, console is clean, as soon as I click on a different one with supertable fields, I will get an error in console

<img width="1687" alt="Screenshot 2022-05-17 at 09 20 03" src="https://user-images.githubusercontent.com/18517642/168764863-d7967360-6248-4b9d-9784-47ddb3986f19.png">

**Comment by engram-design** [comment]
Hmm, yes some JS errors might be the cause of this! I can't _quite_ tell where this error is coming from, but I might start disabling plugins (except Super Table) to see if it's something third-party.

Otherwise, you're welcome to send your database and files to `support@verbb.io` for me to have a look.

**Comment by engram-design** [comment]
Fixed in [3.0.0-beta.4](https://github.com/verbb/super-table/releases/tag/3.0.0-beta.4) but will wait an see the result of your findings.

**Comment by DenyEs** [comment]
I upgraded to the latest version - beta 4 but still no luck. I tried disabling all of my plugins as well to see if I can pinpoint whats causing it but with all plugins disabled (except Supertable) I still have the same issue. I will send the database and files over to you so you s can see what I see.

**Comment by curtishenson** [comment]
I _think_ this might be the same issue I ran into. Haven't tried beta.4 yet but just to add my findings.

Seemed to be caused by two super table fields on the same entry and isn't an issue on Craft 4.0.1

**Comment by curtishenson** [comment]
Tested beta.4 and getting the same error as the screenshot above. As well as throwing this: https://github.com/craftcms/cms/blob/0c089c1a580920b57cf34e49b7a45f418b8adff8/src/web/assets/garnish/src/MenuBtn.js#L44

Also doesn't actually seem related to having 2 super table fields.

I also tried with craft dev branch since MenuBtn.js got an update and got another error, which I think is the same error just happening earlier.

<img width="1341" alt="Screen Shot 2022-05-18 at 12 08 15 PM" src="https://user-images.githubusercontent.com/15751/169137762-662033e0-8e0d-471c-a6b2-7795becfa83a.png">

**Comment by engram-design** [comment]
Thanks @DenyEs I can see this issue, which is a static field with a Matrix layout. I'm actually surprised this hasn't caused an issue up to this point!

Fixed for the next release. To get the fix early, change your `verbb/super-table` requirement in `composer.json` to:

```
"require": {
  "verbb/super-table": "dev-craft-4 as 3.0.0-beta.4",
  "...": "..."
}
```

Then run `composer update`.

**Comment by DenyEs** [comment]
@engram-design Thank you! I just pulled an update and it works!! I checked all of my supertable fields and they all seems to be showing absolutely fine now. Thank you again!

**Comment by curtishenson** [comment]
Fixed for me as well, thank you!

**Comment by engram-design** [comment]
This should be fixed in [3.0.0-beta.5](https://github.com/verbb/super-table/releases/tag/3.0.0-beta.5)
